=== andreyscherbin/JavaWebDevelopment/SecondTaskXML/data/tourist_voucher.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="./tourist_vouchers" xmlns:tns="./tourist_vouchers"
	elementFormDefault="qualified">

	<element name="tourist_voucher" type="tns:TouristVoucher" abstract="true"></element>
	<element name="excursion_voucher" type="tns:ExcursionVoucher" substitutionGroup="tns:tourist_voucher"></element>
	<element name="rest_voucher" type="tns:RestVoucher" substitutionGroup="tns:tourist_voucher"></element>
	<element name="piligrimage_voucher" type="tns:PiligrimageVoucher" substitutionGroup="tns:tourist_voucher"></element>

	<element name="tourist_vouchers">
		<complexType>
			<sequence>
				<element ref="tns:tourist_voucher" minOccurs="16" maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>

	<complexType name="TouristVoucher">
		<sequence>
			<element name="number_voucher" type="tns:NumberVoucher" />
			<element name="country" type="string" />
			<element name="number_days" type="positiveInteger" />
			<element name="number_nights" type="positiveInteger" />
			<element name="cost" type="positiveInteger" />
			<element name="date" type="dateTime" />
		</sequence>
		<attribute name="transport" use="required">
			<simpleType>
				<restriction base="string">
					<enumeration value="air"></enumeration>
					<enumeration value="auto"></enumeration>
					<enumeration value="liner"></enumeration>
					<enumeration value="railway"></enumeration>
				</restriction>
			</simpleType>
		</attribute>
	</complexType>

	<complexType name="RestVoucher">
		<complexContent>
			<extension base="tns:TouristVoucher">
				<sequence>
					<element name="hotel_characteristic" type="tns:HotelCharacteristic" minOccurs="1" maxOccurs="unbounded" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="ExcursionVoucher">
		<complexContent>
			<extension base="tns:TouristVoucher">
				<sequence>
					<element name="city" type="string" />
					<element name="showplace" type="string" />
					<element name="hotel_characteristic" type="tns:HotelCharacteristic" minOccurs="1" maxOccurs="unbounded" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	
	<complexType name="PiligrimageVoucher">
		<complexContent>
			<extension base="tns:TouristVoucher">
				<sequence>
					<element name="city" type="string" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<simpleType name="NumberVoucher">
		<restriction base="ID">
			<pattern value="([A0-9]){10}" />
		</restriction>
	</simpleType>

	<complexType name="HotelCharacteristic">
		<sequence>
			<element name="stars" type="tns:Stars" />
			<element name="is_food" type="boolean" />
			<element name="is_tv" type="boolean" />
			<element name="is_conditioner" type="boolean" />
			<element name="number_place" type="tns:NumberPlace" />
		</sequence>
		<attribute name="type_food" use="optional" default="HB">
			<simpleType>
				<restriction base="string">
					<enumeration value="HB"></enumeration>
					<enumeration value="BB"></enumeration>
					<enumeration value="AI"></enumeration>
				</restriction>
			</simpleType>
		</attribute>
	</complexType>

	<simpleType name="Stars">
		<restriction base="positiveInteger">
			<minInclusive value="1" />
			<maxInclusive value="5" />
		</restriction>
	</simpleType>

	<simpleType name="NumberPlace">
		<restriction base="positiveInteger">
			<minInclusive value="1" />
			<maxInclusive value="3" />
		</restriction>
	</simpleType>
</schema>

=== andreyscherbin/JavaWebDevelopment/SecondTaskXML/data/tourist_voucher.xml
<?xml version="1.0" encoding="UTF-8"?>
<tourist_vouchers xmlns="./tourist_vouchers"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="./tourist_vouchers tourist_voucher.xsd ">

	<rest_voucher transport="air">
		<number_voucher>A999999998</number_voucher>
		<country>BRAZIL</country>
		<number_days>10</number_days>
		<number_nights>10</number_nights>
		<cost>200</cost>
		<date>2021-01-31T22:43:00</date>
		<hotel_characteristic type_food="HB">
			<stars>3</stars>
			<is_food>true</is_food>
			<is_tv>true</is_tv>
			<is_conditioner>true</is_conditioner>
			<number_place>1</number_place>
		</hotel_characteristic>
		<hotel_characteristic type_food="AI">
			<stars>5</stars>
			<is_food>true</is_food>
			<is_tv>true</is_tv>
			<is_conditioner>true</is_conditioner>
			<number_place>3</number_place>
		</hotel_characteristic>
	</rest_voucher>
	
	<excursion_voucher transport="auto">
		<number_voucher>A999999999</number_voucher>
		<country>BELARUS</country>
		<number_days>1</number_days>
		<number_nights>1</number_nights>
		<cost>100</cost>
		<date>2021-01-30T23:43:00</date>
		<city>MINSK</city>
		<showplace>Victory Square</showplace>
		<hotel_characteristic type_food="HB">
			<stars>3</stars>
			<is_food>true</is_food>
			<is_tv>true</is_tv>
			<is_conditioner>true</is_conditioner>
			<number_place>1</number_place>
		</hotel_characteristic>
	</excursion_voucher>

	<excursion_voucher transport="air">
		<number_voucher>A999999997</number_voucher>
		<country>JAPAN</country>
		<number_days>10</number_days>
		<number_nights>10</number_nights>
		<cost>10000</cost>
		<date>2021-03-31T19:43:00</date>
		<city>Yamanashi</city>
		<showplace>Fujiyama</showplace>
		<hotel_characteristic type_food="HB">
			<stars>3</stars>
			<is_food>true</is_food>
			<is_tv>true</is_tv>
			<is_conditioner>true</is_conditioner>
			<number_place>1</number_place>
		</hotel_characteristic>
	</excursion_voucher>

	<piligrimage_voucher transport="air">
		<number_voucher>A999999996</number_voucher>
		<country>ISRAEL</country>
		<number_days>10</number_days>
		<number_nights>10</number_nights>
		<cost>5000</cost>
		<date>2021-04-28T17:43:00</date>
		<city>JERUSALEM</city>
	</piligrimage_voucher>

	<rest_voucher transport="auto">
		<number_voucher>A999999995</number_voucher>
		<country>TURKEY</country>
		<number_days>365</number_days>
		<number_nights>365</number_nights>
		<cost>10000</cost>
		<date>2021-04-28T17:43:00</date>
		<hotel_characteristic>
			<stars>1</stars>
			<is_food>false</is_food>
			<is_tv>false</is_tv>
			<is_conditioner>false</is_conditioner>
			<number_place>1</number_place>
		</hotel_characteristic>
	</rest_voucher>

	<rest_voucher transport="air">
		<number_voucher>A999999994</number_voucher>
		<country>USA</country>
		<number_days>10</number_days>
		<number_nights>10</number_nights>
		<cost>9999999</cost>
		<date>2025-04-28T18:43:00</date>
		<hotel_characteristic type_food="AI">
			<stars>4</stars>
			<is_food>true</is_food>
			<is_tv>true</is_tv>
			<is_conditioner>true</is_conditioner>
			<number_place>3</number_place>
		</hotel_characteristic>
	</rest_voucher>

	<rest_voucher transport="air">
		<number_voucher>A999999993</number_voucher>
		<country>SWEDEN</country>
		<number_days>20</number_days>
		<number_nights>20</number_nights>
		<cost>100000</cost>
		<date>2026-01-28T06:00:00</date>
		<hotel_characteristic>
			<stars>5</stars>
			<is_food>false</is_food>
			<is_tv>false</is_tv>
			<is_conditioner>true</is_conditioner>
			<number_place>1</number_place>
		</hotel_characteristic>
		<hotel_characteristic type_food="BB">
			<stars>4</stars>
			<is_food>true</is_food>
			<is_tv>true</is_tv>
			<is_conditioner>true</is_conditioner>
			<number_place>2</number_place>
		</hotel_characteristic>
		<hotel_characteristic type_food="AI">
			<stars>5</stars>
			<is_food>true</is_food>
			<is_tv>true</is_tv>
			<is_conditioner>true</is_conditioner>
			<number_place>3</number_place>
		</hotel_characteristic>
	</rest_voucher>

	<excursion_voucher transport="railway">
		<number_voucher>A999999992</number_voucher>
		<country>SINGAPORE</country>
		<number_days>20</number_days>
		<number_nights>20</number_nights>
		<cost>1000000</cost>
		<date>2023-04-28T07:00:00</date>
		<city>UKRAINE</city>
		<showplace>Kiev Pechersk Lavra</showplace>
		<hotel_characteristic type_food="BB">
			<stars>1</stars>
			<is_food>false</is_food>
			<is_tv>false</is_tv>
			<is_conditioner>false</is_conditioner>
			<number_place>2</number_place>
		</hotel_characteristic>
	</excursion_voucher>

	<piligrimage_voucher transport="auto">
		<number_voucher>A999999991</number_voucher>
		<country>ITALY</country>
		<number_days>5</number_days>
		<number_nights>5</number_nights>
		<cost>20000</cost>
		<date>2022-06-28T00:00:00</date>
		<city>Holy Land</city>
	</piligrimage_voucher>

	<excursion_voucher transport="air">
		<number_voucher>A999999990</number_voucher>
		<country>INDIA</country>
		<number_days>20</number_days>
		<number_nights>20</number_nights>
		<cost>999999</cost>
		<date>2026-07-28T04:00:00</date>
		<city>Agra</city>
		<showplace>Taj Mahal</showplace>
		<hotel_characteristic type_food="AI">
			<stars>4</stars>
			<is_food>true</is_food>
			<is_tv>true</is_tv>
			<is_conditioner>true</is_conditioner>
			<number_place>2</number_place>
		</hotel_characteristic>
	</excursion_voucher>

	<excursion_voucher transport="air">
		<number_voucher>A999999989</number_voucher>
		<country>CHINA</country>
		<number_days>10</number_days>
		<number_nights>10</number_nights>
		<cost>10000</cost>
		<date>2025-12-31T13:00:00</date>
		<city>Huairou District</city>
		<showplace>Great Wall of China</showplace>
		<hotel_characteristic>
			<stars>1</stars>
			<is_food>false</is_food>
			<is_tv>false</is_tv>
			<is_conditioner>false</is_conditioner>
			<number_place>3</number_place>
		</hotel_characteristic>
	</excursion_voucher>

	<rest_voucher transport="air">
		<number_voucher>A999999988</number_voucher>
		<country>GREECE</country>
		<number_days>20</number_days>
		<number_nights>20</number_nights>
		<cost>20</cost>
		<date>2030-11-30T11:00:00</date>
		<hotel_characteristic>
			<stars>1</stars>
			<is_food>false</is_food>
			<is_tv>false</is_tv>
			<is_conditioner>false</is_conditioner>
			<number_place>2</number_place>
		</hotel_characteristic>
	</rest_voucher>

	<rest_voucher transport="auto">
		<number_voucher>A999999987</number_voucher>
		<country>FRANCE</country>
		<number_days>15</number_days>
		<number_nights>15</number_nights>
		<cost>10000</cost>
		<date>2028-06-30T06:00:00</date>
		<hotel_characteristic>
			<stars>1</stars>
			<is_food>false</is_food>
			<is_tv>false</is_tv>
			<is_conditioner>false</is_conditioner>
			<number_place>2</number_place>
		</hotel_characteristic>
	</rest_voucher>

	<excursion_voucher transport="air">
		<number_voucher>A999999986</number_voucher>
		<country>USA</country>
		<number_days>20</number_days>
		<number_nights>20</number_nights>
		<cost>10000</cost>
		<date>2025-04-30T00:00:00</date>
		<city>New York</city>
		<showplace>Statue of Liberty</showplace>
		<hotel_characteristic type_food="AI">
			<stars>5</stars>
			<is_food>true</is_food>
			<is_tv>true</is_tv>
			<is_conditioner>true</is_conditioner>
			<number_place>3</number_place>
		</hotel_characteristic>
	</excursion_voucher>

	<excursion_voucher transport="auto">
		<number_voucher>A999999985</number_voucher>
		<country>FRANCE</country>
		<number_days>999</number_days>
		<number_nights>999</number_nights>
		<cost>5000</cost>
		<date>2100-01-01T00:00:00</date>
		<city>Paris</city>
		<showplace>tour Eiffel</showplace>
		<hotel_characteristic>
			<stars>5</stars>
			<is_food>true</is_food>
			<is_tv>true</is_tv>
			<is_conditioner>true</is_conditioner>
			<number_place>3</number_place>
		</hotel_characteristic>
	</excursion_voucher>

	<rest_voucher transport="railway">
		<number_voucher>A999999984</number_voucher>
		<country>FINLAND</country>
		<number_days>5</number_days>
		<number_nights>5</number_nights>
		<cost>9000</cost>
		<date>2027-05-23T06:00:00</date>
		<hotel_characteristic type_food="BB">
			<stars>5</stars>
			<is_food>true</is_food>
			<is_tv>true</is_tv>
			<is_conditioner>true</is_conditioner>
			<number_place>3</number_place>
		</hotel_characteristic>
	</rest_voucher>
</tourist_vouchers>
